<?php

    require 'dbconnect.php';




    if(isset($_POST['imgname']) && !empty($_POST['imgname']))
    {


        echo('<head>
        <title>Image Upload</title>
        <link rel="stylesheet" href="style.css">
        </head>');
        // get the file
        $theFileName = $_FILES['img']['tmp_name'];

        $imagesize = filesize($theFileName);

        $imagetype = mime_content_type($theFileName);

        $sql = 'SELECT user_id FROM tbl_user WHERE username LIKE "' . $_SESSION['username'] . '"';

        // query the database
        $rs = $pdo->query($sql);

        while($row = $rs->fetch())
        {
            $userid = $row['user_id'];
        }
        

        // encode to base 64
        // base 64 is a common form of handling data and is used
        // to ensure that the handling of bits across the network are correct

        $img = base64_encode(file_get_contents($_FILES['img']['tmp_name']));

        // ------------------------------------------------
        // sql statement

        

        // *** AUTO GENERATED BY PHP_SQL_Code_Generator.java *** 
        $sql_Insert =  	"INSERT INTO tbl_img".
        "(imgname,imgdesc,img,imgtype,imgsize,user_id) ".
        "VALUES(:imgname,:imgdesc,:img,:imgtype,:imgsize,:user_id)";

        $sql_Insert =  $pdo->prepare($sql_Insert);
        $imgname = filter_var($_POST['imgname'], FILTER_SANITIZE_STRING);
        $dogbreed = filter_var($_POST['imgdesc'], FILTER_SANITIZE_STRING);
  

        $sql_Insert->bindparam(":imgname",$imgname);
        $sql_Insert->bindparam(":imgdesc",$dogbreed);
        $sql_Insert->bindparam(":img",$img,PDO::PARAM_LOB);
        $sql_Insert->bindparam(":imgtype",$imagetype);
        $sql_Insert->bindparam(":imgsize",$imagesize);
        $sql_Insert->bindparam(":user_id",$userid);

        try
        {
            $upcheck = $sql_Insert->execute();
        }
        catch (PDOException $e)
        {
            $upcheck = false;
            echo('<div id="errorbox">Failed: '. $e->getMessage() .'</div>');
        }
        // *** END AUTO GENERATED CODE ***


        if ($upcheck)
        {
            echo('
            <div class="top-bar">
                <nav class="navigation">
                    <a href="index.html">Home</a>
                    <a href="imginput.php">Add Images</a>
                    <a href="getimg.php">View Images</a>
                    <a href="logout.php">Logout</a>
                </nav>
            </div>
            <br>
            <div id="successbox">File uploaded correctly <a href="getimg.php">View Images</a></div><br>
            ');
        }
        else
        {
            echo('<br> <div id="errorbox">************* FILE UPLOAD FAILED **************</div>');
        }

    }
    else
    {
        echo('
            <!DOCTYPE html>
            <html>
                <head>
                    <title>Image Upload</title>
                    <link rel="stylesheet" href="style.css">
                </head>
                <body>
                    <div class="top-bar">
                        <nav class="navigation">
                            <a href="index.html">Home</a>
                            <a href="imginput.php">Add Images</a>
                            <a href="getimg.php">View Images</a>
                            <a href="logout.php">Logout</a>
                        </nav>
                    </div>

                    <div class="content">
                        <form accept="imginput.php" method="POST" enctype="multipart/form-data">
                            <table id=imgtable>
                                <tr>
                                    <td>Image Name</td>
                                    <td><input  type="text" size="25" name="imgname" value="" required>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Image Description</td>
                                    <td><input  type="text" size="25" name="imgdesc" value="" required></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>
  
                                    <input  type="file" name="img" accept=".jpg,.jpeg,.png" oninput="pic.src=window.URL.createObjectURL(this.files[0])" required>
                                    
                                    </td>
                                    
                                </tr>
                                <tr>
                                    <td colspan="2"><img id="pic" /></td>
                                </tr>
                                <tr>
                                    <td colspan="2"><input type="submit" value="Enter"></td>
                                </tr>
                                
                            </table>
                        </form>

                    
                    </div>
                </body>
            </html>
        ');
    }
?>